Russian translation
Sturmlilie/TIS-3D pull request #1
Opened 2020-08-24 20:11 UTC by Sturmlilie

Translation by `kazmurenko` on CurseForge.

2020-08-25 20:17 UTC, Yoghurt4C requested changes
<a><img src="https://cdn.discordapp.com/attachments/360438464572817408/747236109276151828/unknown.png" alt="" width=250 height=500></a>

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.book_code": "Код библия",
```suggestion
    "item.tis3d.book_code": "Библия Кода",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.key_creative": "Скелетоный ключ",
```suggestion
    "item.tis3d.key_creative": "Скелетный Ключ",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_bundled_redstone": "Связной редестоун модуль",
```suggestion
    "item.tis3d.module_bundled_redstone": "Модуль Красного Многожильного Кабеля",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.book_manual": "TIS-3D Справочное руководство",
```suggestion
    "item.tis3d.book_manual": "Справочное Руководство TIS-3D",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_audio": "Звуковой модуль",
```suggestion
    "item.tis3d.module_audio": "Звуковой Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_display": "Дисплей модуля",
```suggestion
    "item.tis3d.module_display": "Дисплейный Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_execution": "Выполнененый модуль",
```suggestion
    "item.tis3d.module_execution": "Экзекуционный Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_infrared": "Инфакрасный модуль",
```suggestion
    "item.tis3d.module_infrared": "Инфракрасный Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_keypad": "Клавиатурный модуль",
```suggestion
    "item.tis3d.module_keypad": "Клавиатурный Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_queue": "Модуль очереди",
```suggestion
    "item.tis3d.module_queue": "Модуль Очереди",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_random": "Случайный модуль",
```suggestion
    "item.tis3d.module_random": "Модуль Случайности",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_random_access_memory": "Модуль памяти",
```suggestion
    "item.tis3d.module_random_access_memory": "Модуль Оперативной Памяти",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_read_only_memory": "ПЗУ модуль",
```suggestion
    "item.tis3d.module_read_only_memory": "Модуль ПЗУ",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_redstone": "Редстоун модуль",
```suggestion
    "item.tis3d.module_redstone": "Краснопыльный Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_sequencer": "Секвенсор модуль",
```suggestion
    "item.tis3d.module_sequencer": "Секвенсорный Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_serial_port": "Серийный порт модуль",
```suggestion
    "item.tis3d.module_serial_port": "Модуль Серийного Порта",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_stack": "Стак модуль",
```suggestion
    "item.tis3d.module_stack": "Стекируемый Модуль",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_terminal": "Терминал модуль",
```suggestion
    "item.tis3d.module_terminal": "Модуль Терминала",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_timer": "Таймер модуль",
```suggestion
    "item.tis3d.module_timer": "Модуль Таймера",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.compiler.error": "Ошибка компиляции@%s:%s-%s: ",
```suggestion
    "tis3d.compiler.error": "Ошибка компиляции @%s:%s-%s: ",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.compiler.invalid_format": "Неожиданный маркер",
```suggestion
    "tis3d.compiler.invalid_format": "Недействительный токен",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.compiler.label_not_found": "Неопределеная ярлык",
```suggestion
    "tis3d.compiler.label_not_found": "Ярлык не определён",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.compiler.label_duplicate": "Ярлык уже определен",
```suggestion
    "tis3d.compiler.label_duplicate": "Ярлык уже определён",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.compiler.parameter_invalid": "Неверный регистр",
```suggestion
    "tis3d.compiler.parameter_invalid": "Неверный реестр",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.compiler.too_many_columns": "Слишком длинная линия",
```suggestion
    "tis3d.compiler.too_many_columns": "Линия cлишком длинна",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.controller.status.too_complex": "Слишком сложный",
```suggestion
    "tis3d.controller.status.too_complex": "Сложность слишком велика",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.manual.home": "Дом",
```suggestion
    "tis3d.manual.home": "Начальная Страница",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.manual.blocks": "Блокы",
```suggestion
    "tis3d.manual.blocks": "Блоки",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.manual.serial_protocols": "Последовательные протоколы",
```suggestion
    "tis3d.manual.serial_protocols": "Серийные Протоколы",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.manual.warning.missing.block": "Блокировать недоступно.",
```suggestion
    "tis3d.manual.warning.missing.block": "Блок отсутствует.",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.manual.warning.missing.tag": "Запись тега недуступно.",
```suggestion
    "tis3d.manual.warning.missing.tag": "Таговая запись отсутствует",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.tooltip.book_code": "§7Используйте книгу об установленном исполнительном модуле, чтобы получить копию.",
```suggestion
    "tis3d.tooltip.book_code": "§7Используй книгу на установленном Экзекуционном Модуле, чтобы получить копию.",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.tooltip.book_manual": "§7Используйте книгу на блоке контроллера, чтобы получить копию.",
```suggestion
    "tis3d.tooltip.book_manual": "§7Используй книгу на блоке Контроллера, чтобы получить копию.",
```

2020-08-25 20:17 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.tooltip.key": "§7Подкрадитесь, удерживая, чтобы переключить приемные порты на лицевой стороне корпуса."
```suggestion
    "tis3d.tooltip.key": "§7Используется для переключения приёмных портов на сторонах Обшивок в режиме скрытности игрока."
```

2020-08-27 14:32 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_execution": "Выполнененый модуль",
Better "Исполняющий Модуль"

2020-08-27 14:33 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_redstone": "Редстоун модуль",
"Редстоуновый Модуль" is more conventional

2020-08-27 14:34 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_bundled_redstone": "Связной редестоун модуль",
A bit unconventional. Mojang calls it "Редстоун". So maybe "Модуль Многожильного Редстоунового Кабеля"

2020-08-27 14:35 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_stack": "Стак модуль",
"Модуль Стека"

2020-08-27 14:35 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "block.tis3d.controller": "Контролер",
"Контроллер" - correct spelling

2020-08-27 14:37 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "block.tis3d.controller": "Контролер",
```suggestion
    "block.tis3d.controller": "Контроллер",
```

2020-08-27 14:38 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.manual.warning.missing.tag": "Запись тега недуступно.",
"Тег отстутствует" - correct spelling + less clunky

2020-08-27 14:39 UTC, falseresync commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "tis3d.tooltip.book_code": "§7Используйте книгу об установленном исполнительном модуле, чтобы получить копию.",
"... Исполняющем Модуле ..."

2020-08-27 14:39 UTC, Yoghurt4C commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "item.tis3d.module_bundled_redstone": "Связной редестоун модуль",
https://minecraft-ru.gamepedia.com/Красная_пыль

2020-08-27 14:44 UTC, falseresync commented
@Yoghurt4C check the comments on the suggestions, I didn't use the suggestion tool anywhere :P

2020-08-28 12:43 UTC, Sturmlilie commented on src/main/resources/assets/tis3d/lang/ru_ru.json
> +    "block.tis3d.controller": "Контролер",
https://en.wiktionary.org/wiki/%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D1%91%D1%80
https://en.wiktionary.org/wiki/%D0%BA%D0%BE%D0%BD%D1%82%D1%80%D0%BE%D0%BB%D0%BB%D0%B5%D1%80
they're two distinct words (I think?), anyway false's suggestion seems more appropriate

2020-08-28 13:56 UTC, closed without merging